language: php

sudo: false

php:
  - 7.1

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

  fast_finish: true

  allow_failures:
    - php: 7.1

before_install:
  - composer global require hirak/prestissimo

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run ; fi
  - if [[ $PHPCS == 1 ]]; then composer cs-check ; fi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false
